---
abstract: 'A mock RabbitMQ implementation for use when testing.'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Net-RabbitMQ
requires:
  Moose: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/gphat/test-net-rabbitmq/issues
  homepage: https://github.com/gphat/test-net-rabbitmq
  repository: https://github.com/gphat/test-net-rabbitmq.git
version: 0.10
